[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lidao"
authors = [{name = "JavGuerra", email = "correo@electronico.es"}]
dynamic = ["version", "description"]
